getinvolved.html
index.html
installation.html
nightly.html
releases.html

The link from the github badge is incorrect

github: correct url for github badge

---

.travis.yml
README.md
package.json

for now, travis will just automatically lint new PR's

travis: add travis CI

---

dist/js/api.js

Fix empty JSON from /api

---

api.html
getinvolved.html
index.html
installation.html
nightly.html
package.json
releases.html

All mentions of GetOpenJDK replaced with AdoptOpenJDK

Rename to AdoptOpenJDK

---

src/handlebars/index.handlebars
src/handlebars/partials/menu.handlebars
src/scss/styles-2-index.scss

This should be merged **after** the [currently open API PR](https://github.com/AdoptOpenJDK/openjdk-api/pull/11).
On [staging](https://staging.adoptopenjdk.net).

Add API links to homepage and menu

---

src/handlebars/sponsors.handlebars

staged here: https://staging.adoptopenjdk.net/sponsors.html

add Linaro blurb

---

src/handlebars/partials/footer.handlebars

Added the script to the end of the footer partial, for inclusion in every page, at the very end of the page-load process.
Adding to Staging just to check that it doesn't cause any unexpected issues.

Add Google Analytics (Fixes #116)

---

src/handlebars/installation.handlebars
src/handlebars/partials/header.handlebars
src/scss/styles-1-large-main.scss

[STAGING](https://staging.adoptopenjdk.net/installation.html)
Changed to dark-theme background colours for all code elements

Add highlight.js to Installation page (Fixes #119, Fixes #118)

---

src/handlebars/404.handlebars

On [Staging](https://staging.adoptopenjdk.net/404.html)

Add 404 links to home page (Fixes #131)

---

src/handlebars/getinvolved.handlebars
src/handlebars/partials/footer.handlebars
src/js/archive.js
src/js/nightly.js
src/scss/styles-11-archive.scss

On [Staging](https://staging.adoptopenjdk.net)
As per George's request, following a discussion:
**Nightly:**
Removed release details section
Made checksum and release date their own columns for correct alignment
**Archive:**
Release details block removed
**Footer:**
Links for people who spot issues in website

Multiple minor changes to layout (Fixes #125)

---

gulpfile.js

we need to prevent search engines from indexing our 404.html page and also our banner.html

add robots.txt

---

src/handlebars/archive.handlebars
src/js/0-global.js
src/js/archive.js
src/scss/styles-11-archive.scss

[STAGING](https://staging.adoptopenjdk.net/archive.html) (currently set to max. 5 archive entries per page, so the pagination addition is hidden as there is only 1 page)
This is what it will look like once there are more than 5 archive entries:

Add Archive pagination, comment out platform filter (Fixes #126)

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

small fixup in contributing.md
also adds PR and issue templates
adds eslint fixup

contributing.md fixup

---

.eslintrc.yml
src/handlebars/archive.handlebars
src/handlebars/partials/jck-tick.handlebars
src/handlebars/releases.handlebars
src/js/0-global.js
src/js/archive.js
src/js/index.js
src/js/releases.js

Sort Latest and Archive platforms into specified order, add JCK tick links - Fixes #97, Fixes #147

---

src/js/0-global.js

Add AIX platform

---

src/handlebars/installation.handlebars

staging: https://staging.adoptopenjdk.net

add aix untar instructions

---

CONTRIBUTING.md
src/handlebars/index.handlebars
src/handlebars/partials/header.handlebars
src/handlebars/partials/meta-description.handlebars
src/handlebars/releases.handlebars
src/js/releases.js
src/scss/styles-4-releases.scss
src/scss/styles-5-medium.scss

[STAGING](https://staging.adoptopenjdk.net/releases.html)
Primary change is adding a new grid system for the Latest page. Clicking on a platform now 'switches' to the platform view, rather than displaying it below.
The horizontally scrolling platform selector is now gone, and all platforms will now always be visible on-screen in the grid selector.

Latest page grid system update

---

src/handlebars/archive.handlebars
src/handlebars/nightly.handlebars
src/js/archive.js
src/js/nightly.js
src/js/releases.js

Add var tags to prevent every date being translated separately

---

src/js/releases.js

Add missed var tag

---

src/handlebars/archive.handlebars
src/handlebars/index.handlebars
src/handlebars/partials/menu.handlebars
src/js/archive.js
src/js/index.js
src/scss/styles-1-large-main.scss
src/scss/styles-11-archive.scss

[ON STAGING](https://staging.adoptopenjdk.net) 
Added a link to the blog in the Home Page and the Menu.

Adding Links to Blog

---

src/js/archive.js
src/js/index.js
src/js/nightly.js
src/js/releases.js
src/json/config.json
src/scss/styles-1-large-main.scss

Adding Variant OpenJDK9 to config.json and unhide selectors.

Adding Variant For OpenJDK9

---

src/handlebars/releases.handlebars
src/js/archive.js
src/js/index.js
src/js/installation.js
src/js/nightly.js
src/js/releases.js
src/json/config.json
src/scss/styles-1-large-main.scss
src/scss/styles-4-releases.scss

Configured Installers to change with variant.

Configure Installers for OpenJDK9

---

src/handlebars/about.handlebars

Fix typo in the About page

---

src/js/archive.js
src/js/nightly.js
src/js/releases.js

https://staging.adoptopenjdk.net/index.html?variant=openjdk9-openj9

update links to consider variant

---

.eslintrc.yml
src/handlebars/releases.handlebars
src/js/0-global.js
src/js/releases.js
src/json/config.json

Added link to Eclipse OpenJ9 Website

---

src/js/0-global.js
src/json/config.json

Set OpenJDK 9 with Hotspot to default

---

src/js/0-global.js
src/json/config.json

Changing default variant

---

src/handlebars/getinvolved.handlebars
src/handlebars/slack.handlebars

This PR add's a Slackin page to our website: https://staging.adoptopenjdk.net/slack.html

add slackin page

---

src/handlebars/partials/footer.handlebars
src/handlebars/slack.handlebars

fixes: #203
fixes: #204
staging: https://staging.adoptopenjdk.net/slack.html

a few fixes to the slack page

---

src/handlebars/support.handlebars
src/js/releases.js
src/scss/styles-7-support.scss

Thanks @mstoodle for the wording!
Staging: https://staging.adoptopenjdk.net/support.html

Update support page quality statements around JCK testing 

---

src/scss/styles-2-index.scss

Fixes https://github.com/AdoptOpenJDK/openjdk-website/issues/221

Stop version number word-wrapping

---

src/json/config.json

This works, although at present it can't find the json file for releases as we have not done a release. Nightlies are "on the way" once the pipeline goes through the whole process successfully (PR for website-backend has just been updated to handle this release under https://github.com/AdoptOpenJDK/openjdk-website-backend/pull/9) and the release job has been updated for the new release

Add openjdk10-openj9

---

CONTRIBUTING.md
Dockerfile

…Node and other stuff on computer, but still want to contribute
Also updated Contribution instructions on how to use Docker in development

Added init Docker file that can be used if you don't want to install Node but want to contribute

---

gulpfile.js

fix gulfile to run from current dest

---

src/handlebars/index.handlebars
src/js/index.js
src/scss/styles-4-releases.scss

This PR adds the JCK tick to the landing page
closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/225

add jck tick to landing pages

---

gulpfile.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/196
OLD: https://adoptopenjdk.net/sitemap.xml
NEW: https://staging.adoptopenjdk.net/241/sitemap.xml

prevent banner.html from appearing in sitemaps

---

src/handlebars/index.handlebars

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/216

fix bottom links

---

src/handlebars/support.handlebars
src/scss/styles-7-support.scss

update support to match https://docs.google.com/document/d/19zO0yZidQEmDEVx8whnbsGDR2HpnQmP2mJ0nvDeQfsE/edit#
This is missing the links at the bottom as I am waiting for @tellison to let me know what links are needed.

update support page

---

src/handlebars/partials/header.handlebars

add hotjar heatmap tracking

---

src/json/config.json

- needs to be co-ordinated with a [website-backend PR](https://github.com/AdoptOpenJDK/openjdk-website-backend/pull/14) 
Signed-off-by: smlambert <slambert@gmail.com>

WIP: Update to json config to support linux LargeHeap & win32 builds

---

src/js/archive.js
src/js/releases.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/260

add error exception to releases pages

---

src/handlebars/nightly.handlebars
src/js/0-global.js
src/js/archive.js
src/js/nightly.js
src/js/releases.js
src/json/config.json

Modify code to first check the new `openjdk<x>-binaries` repos to look for releases, if none can be found in those locations default to the old repos.

Read new repositories

---

src/handlebars/nightly.handlebars
src/js/0-global.js
src/js/archive.js
src/js/nightly.js
src/js/releases.js
src/json/config.json

This reverts commit 6b23dbd3b1adb1012173877f832412bbbcb3aadb.

Revert "WIP - Read new repositories (#266)"

---

src/js/0-global.js
src/js/archive.js
src/js/index.js
src/js/installation.js
src/js/nightly.js
src/js/releases.js

Work in progress, also dependent on https://github.com/AdoptOpenJDK/openjdk-api/pull/71

Initial cut of using api as source of data for the website

---

src/handlebars/support.handlebars

Update Support Policy

---

CONTRIBUTING.md
src/handlebars/getinvolved.handlebars
src/handlebars/partials/menu.handlebars

Fix Documentation

---

src/handlebars/index.handlebars

Add note on nightlies; improves discoverability

---

src/json/config.json

Add Java 11 to the available versions list

---

src/handlebars/banner.handlebars

Java 11 is now out

---

src/json/config.json

change searchable name for Linux LH

---

src/scss/styles-10-sponsors.scss

Fix link colours for sponsors

---

src/json/config.json

change macOS PATH command

---

src/handlebars/support.handlebars

jcK Statement

---

gulpfile.js
package.json
src/json/config.schema.json

This relates to #313 
* Added a config.schema.json file and added some patterns to validate against. Some of the constraints are pretty loose but I didn't want to make too many assumptions about their formatting. I tried to base the schema descriptions on the contributing guide as much as possible.
* Created a `json-validate` task in the gulpfile that validates config.json against config.schema.json. It uses the assertion libraries to invoke test failures, and `ajv` (schema validator) and `plugin-error` were also added to devDependencies to support the validation task.
I wasn't sure how to add the task to the CI configuration without tacking it onto the existing npm test script, but it can be run locally if anyone wants to mess with various things to see the output. There's also a few …

Add config.json schema and validation task

---

src/handlebars/support.handlebars

Improve wording

---

gulpfile.js
package-lock.json
package.json
src/js/0-global.js
src/js/archive.js
src/js/index.js
src/js/installation.js
src/js/nightly.js
src/js/releases.js
src/json/config.json
src/json/config.schema.json

Still todo: remove searchableName entirely when we expose JCK information via the api

Detect platform based on attributes rather than matching on file name

---

package-lock.json
package.json
src/handlebars/support.handlebars

new JCK statement

---

src/handlebars/archive.handlebars
src/handlebars/index.handlebars
src/handlebars/installation.handlebars
src/handlebars/nightly.handlebars
src/handlebars/releases.handlebars
src/js/0-global.js
src/js/index.js
src/json/config.json
src/scss/styles-1-large-main.scss
src/scss/styles-2-index.scss
src/scss/styles-5-medium.scss
src/scss/styles-6-small.scss

As per issue #307 I've added radio buttons in place of the drop down menu on the various pages it occurs. 
I've not implemented the `Help Me Choose` section yet as I was asked to just focus on the radio buttons for now, and there seems to be a separate issue for that section. 
I've tested these changes on: 
- Chrome
- Safari
- FireFox
- Internet Explorer
- Microsoft Edge
- iPhone
- iPad

Add radio buttons to website for variant selectors

---

package-lock.json
package.json
src/handlebars/releases.handlebars
src/js/0-global.js
src/js/index.js
src/js/releases.js
src/scss/styles-4-releases.scss

Ensure that latest release per platform is displayed regardless of release date or version

---

src/handlebars/sponsors.handlebars

Drop jClarity down

---

CONTRIBUTING.md

Update CONTRIBUTING.md to reference config.json instead of platform.json

---

src/handlebars/support.handlebars
src/scss/styles-7-support.scss

To help users understand which binaries run on
which architectures and distributions.

[WIP] Add platform support tables to support page

---

src/handlebars/sponsors.handlebars

remove lightbend

---

src/handlebars/archive.handlebars
src/handlebars/releases.handlebars
src/js/archive.js
src/js/releases.js

show installers on website

---

package-lock.json
package.json
src/handlebars/index.handlebars

Update website with packages and Status link

---

src/handlebars/archive.handlebars
src/handlebars/releases.handlebars
src/js/archive.js
src/js/common.js
src/js/index.js
src/scss/styles-1-large-main.scss
src/scss/styles-11-archive.scss
src/scss/styles-4-releases.scss

various UI changes + make installer default download on homepage

---

src/handlebars/support.handlebars

Link updates to support

---

src/handlebars/partials/header.handlebars
src/handlebars/partials/social-bar.handlebars

change youtube url

---

src/handlebars/nightly.handlebars
src/js/nightly.js

add installers for nightly builds

---

src/js/common.js
src/json/config.json

closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/417

add jdk12 support to the website

---

src/js/archive.js

fix dash link

---

gulpfile.js

allow robots access to social image

---

package-lock.json
src/handlebars/index.handlebars
src/handlebars/installation.handlebars
src/handlebars/migration.handlebars
src/handlebars/partials/menu.handlebars
src/handlebars/support.handlebars

Create an HTML page for the migration content so that
individual contributors can update it with progress for
the different components that are being worked on.
E.g. IcedTea-web, fonts, OpenJFX
Minor changes to other pages that mention migration.
Signed-off-by: Sue Chaplain <sue_chaplain@.uk.ibm.com>

Convert migration PDF to HTML to aid contribution

---

src/handlebars/partials/header.handlebars

fix facebook structured data

---

.gitignore
gulpfile.js
package-lock.json
package.json
robots.txt

Fixes an issue where the twitter cards aren't showing.

manually set robots.txt

---

.github/PULL_REQUEST_TEMPLATE.md

add permission for logo check

---

src/handlebars/logos.handlebars
src/scss/styles-14-logos.scss
src/scss/styles-9-testimonials.scss

Some minor phone UI improvements.

minor UI improvements

---

package-lock.json
package.json

Fix browser-sync

---

src/handlebars/partials/header.handlebars

remove banner

---

src/handlebars/users.handlebars

Added AiPSafe logo.
- [ x ] permission has been obtained to add new logo (if applicable)

Add AiPSafe logo.

---

src/handlebars/upstream.handlebars

Improve EA readibility

---

src/handlebars/upstream.handlebars

That build includes an important performance regression fix.

Change 8u official release to 8u212-b04

---

src/handlebars/upstream.handlebars

fix ea links

---

CONTRIBUTING.md
package-lock.json
package.json
src/handlebars/installation.handlebars
src/js/common.js
src/js/installation.js
src/json/config.json
src/json/config.schema.json

Due to the fact client cannot download sha256.txt file (see https://github.com/AdoptOpenJDK/openjdk-website/issues/422#issuecomment-473655077), the changes are not finished, just need to parse the file and replace FILEHASH on the `autoResultCommand` text.

PR for 422

---

src/json/config.json

closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/480

fixed capitalization for issue 

---

src/handlebars/upstream.handlebars

Add 8u222-b02 and 11.0.4+2 EA builds to upstream.html

---

package-lock.json
src/handlebars/icedtea-web.handlebars
src/handlebars/partials/menu.handlebars

add icedtea-web page

---

src/handlebars/installation.handlebars

Update the installation page to add instructions for
DEB and RPM.
Tidy up some HTML tags for consistency.
Closes: #494

Add RPM and DEB install instructions

---

src/handlebars/upstream.handlebars
src/scss/styles-13-upstream.scss

This also restructures the table a bit with updated styling so
it's easier to navigate with these added options.

Add JRE tarballs to upstream.html

---

CONTRIBUTING.md
src/handlebars/about.handlebars
src/handlebars/archive.handlebars
src/handlebars/getinvolved.handlebars
src/handlebars/icedtea-web.handlebars
src/handlebars/index.handlebars
src/handlebars/installation.handlebars
src/handlebars/logos.handlebars
src/handlebars/migration.handlebars
src/handlebars/nightly.handlebars
src/handlebars/partials/header.handlebars
src/handlebars/quality.handlebars
src/handlebars/release_notes.handlebars
src/handlebars/releases.handlebars
src/handlebars/sponsors.handlebars
src/handlebars/support.handlebars
src/handlebars/supported_platforms.handlebars
src/handlebars/upstream.handlebars
src/scss/styles-1-large-main.scss

These changes primarily consist of fixes for accessibility and invalid HTML tag placement, and should have little to no effect on visible layout.
* Add missing `alt` attribute to some images
* Fix `<p>` tags wrapping unsupported child elements
* Use `<p>` for text paragraphs in place of implicit `<br/>` typesetting
* Fix various misplaced or malformed tags
* Update some incorrect titles and anchor refs
* Use CSS `:hover` selector to show anchor icons instead of inlined mouse event scripts
* Fix CONTRIBUTING.md showing `bash` syntax hints as commands in code blocks

Improve HTML validity and fix incorrect titles/anchors

---

src/handlebars/testimonials.handlebars
src/handlebars/users.handlebars

fix alphabetical order and add more logos

---

package-lock.json
package.json
src/handlebars/release_notes.handlebars

Redo source code tar PR

---

src/handlebars/upstream.handlebars

A new round of upstream EA builds. Please review!

Update to JDK 11.0.4+8 and JDK 8u222-b06 EA builds

---

src/handlebars/users.handlebars

update aipsafe logo

---

src/handlebars/testimonials.handlebars
src/handlebars/users.handlebars

promote societe generale to testimonials page

---

src/handlebars/sponsors.handlebars

add sponsorship email to sponsors page

---

src/handlebars/icedtea-web.handlebars

Add ITW 1.8.2

---

src/handlebars/users.handlebars

Adds the Bison Group logo

---

src/js/common.js
src/js/index.js

fix linter issues

---

src/handlebars/users.handlebars

Add Open Systems logo

---

src/handlebars/icedtea-web.handlebars

update ITW to 1.8.3

---

src/handlebars/upstream.handlebars

New round of upstream EA builds. Please review!

Update to JDK 11.0.5+3 and JDK 8u232-b03 EA builds

---

src/handlebars/upstream.handlebars

Another round of EA builds updates.

Update to JDK 11.0.5+4 and JDK 8u232-b04 EA builds

---

src/handlebars/installation.handlebars

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1262
(Also adjusted formatting on the repo file details to allow cut & pasting)

Add missing install instructions for yum-based distributions

---

src/json/config.json

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Add jdk13 support

---

src/handlebars/release_notes.handlebars

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Add jdk13 release notes

---

src/handlebars/upstream.handlebars

Update to JDK 8u232-b06 EA builds

---

src/handlebars/upstream.handlebars

Update to JDK 11.0.5+9 and JDK 8u232-b07 EA builds

---

src/handlebars/users.handlebars

move radiant fleet logo to be alphabetical

---

src/handlebars/testimonials.handlebars
src/scss/styles-9-testimonials.scss

add car gurus testimonial

---

src/handlebars/testimonials.handlebars

add cargurus logo to testimonials

---

src/handlebars/jmc.handlebars

The RCP update site should not be listed on the website (#596)

---

src/js/index.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/601

ensure that latest button always returns the latest asset

---

src/handlebars/installation.handlebars

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/597

fix language list link

---

src/js/archive.js
src/js/index.js
src/js/nightly.js
src/js/releases.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/532

switch Mib to Mb

---

src/js/index.js

Fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/611

always serve JDK by default

---

src/handlebars/jmc.handlebars

Update JMC to point to the latest 8.0.0-SNAPSHOT

---

src/handlebars/upstream.handlebars

Another round of 8u EA builds update.

Update to JDK 8u242-b02 EA builds

---

src/handlebars/support.handlebars

Update link to support issues repository

---

src/handlebars/upstream.handlebars

Latest round of JDK 11 EA builds.

Update to JDK 11.0.6+7 EA builds

---

src/handlebars/upstream.handlebars

Latest round of EA builds for JDK 11.

Update to JDK 11.0.6+8 EA builds

---

src/handlebars/support.handlebars

Fixes https://github.com/AdoptOpenJDK/openjdk-website/issues/630

Update support page with October 2019 releases

---

src/handlebars/installation.handlebars

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1454

Fix macos pkg installation path

---

src/handlebars/support.handlebars

Adjust footnotes to be in superscript on the support table

---

src/handlebars/faq.handlebars
src/handlebars/index.handlebars

Resolves https://github.com/AdoptOpenJDK/openjdk-website/issues/371

Add initial version of the adoptopenjdk FAQ

---

src/handlebars/faq.handlebars

@jerboaa FYI This supercedes the last PR that you commented on, and includes the fixes to your comments

FAQ: More updates following review

---

src/handlebars/partials/header.handlebars

Draft pull request for Jan 2020 security release.

Add banner to notify users about pending Jan CPU release

---

src/js/releases.js
src/js/upstream.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/659

fix dropdown filter

---

src/handlebars/installation.handlebars
src/handlebars/partials/modal.handlebars
src/js/common.js
src/js/installation.js
src/scss/styles-4-releases.scss

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/663

fix installation page and add copy feature to checksums

---

src/handlebars/supported_platforms.handlebars

Add Windows Server 2019 to supported platforms

---

src/handlebars/partials/modal.handlebars
src/scss/styles-4-releases.scss

Prevents users from accidentally adding inserting additional text into the checksum box and then copying it.

checksum modal css tweaks

---

src/js/common.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/661

fix nightly jvm_impl parsing

---

src/handlebars/partials/header.handlebars

Reverts AdoptOpenJDK/openjdk-website#657

Revert "Add banner to notify users about pending Jan CPU release"

---

src/handlebars/releases.handlebars
src/js/releases.js
src/json/config.json
src/json/config.schema.json
src/scss/styles-4-releases.scss

add large heap binaries

---

src/json/config.json

Add OpenJ9 AArch64 large heap builds to Nightly builds

---

package-lock.json
package.json
src/handlebars/release_notes.handlebars

Fixes #673

---

src/handlebars/support.handlebars

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>
Updated support page with latest and next releases...

Update support table

---

src/handlebars/installation.handlebars

Use $releasever and $basearch in Centos example

---

package-lock.json
package.json
src/json/config.json

Add 14 Support to nightly page

---

src/json/config.json

Land this once the March JDK14 release is out

mark jdk14 as latest

---

src/json/config.json

Reverts AdoptOpenJDK/openjdk-website#690

Revert "mark jdk14 as latest"

---

package-lock.json
package.json
src/handlebars/release_notes.handlebars
src/handlebars/supported_platforms.handlebars
src/json/config.json

Java 14 release notes and enablement

---

src/handlebars/jmc.handlebars

Adding @thegreystone tutorial link on Mission Control page, as discussed on Slack.

JMC tutorial link

---

src/handlebars/faq.handlebars

FAQ: Adjust wording about OpenJFX providers

---

src/handlebars/partials/header.handlebars

Draft for April 2020 quarterly patch update

Add release banner

---

src/js/nightly.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/703

show correct nightly binary type

---

src/handlebars/sponsors.handlebars

update wording for Packet

---

src/json/config.json

bump supported win version to 2012r2

---

src/handlebars/archive.handlebars
src/js/archive.js

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/708

add EA tag to archive page

---

src/handlebars/partials/header.handlebars

remove release banner

---

migration.html

Update JMC URL

---

src/handlebars/supported_platforms.handlebars

Add latest ubuntu

---

src/handlebars/jmc.handlebars

Adds additional links the the latest 7.1.1 final JMC version.

Implements #724

---

src/handlebars/jmc.handlebars

- [x ] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

Fixes #726 in for the changed artefact numbers

---

src/js/common.js
src/json/config.json

closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/716

serve jdk11 as default

---

src/handlebars/support.handlebars

Update release dates

---

src/handlebars/partials/header.handlebars

add announcement banner

---

package-lock.json
package.json
src/handlebars/partials/header.handlebars

Add Banner and update insecure deps

---

src/handlebars/getinvolved.handlebars

Fix links to support repository

---

src/handlebars/slack.handlebars

fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/759

change slack login

---

src/handlebars/installation.handlebars

Added link to releases.html on top of installation.html.

add link to ./releases.html

---

src/handlebars/faq.handlebars

Fix typo in FAQ

---

src/handlebars/support.handlebars

Update OpenJDK 15 support notes. I'm not 100% sure about the "next release" column - will OpenJDK 15 follow the regular quarterly update cycle?

Update OpenJDK 15 support notes

---

src/handlebars/faq.handlebars

faq: clarify use of _adopt suffix in tags

---

package-lock.json
src/handlebars/release_notes.handlebars

Add Security notes

---

src/handlebars/partials/header.handlebars

Reverts AdoptOpenJDK/openjdk-website#813

Revert "Add banner for October 2020 releases"

---

package-lock.json
package.json
src/handlebars/release_notes.handlebars

Add lots of missing release notes via foojay.io

---

src/handlebars/partials/header.handlebars
src/handlebars/support.handlebars

Updates to support pages for October 2020 releases

---

src/handlebars/faq.handlebars

Update link to OpenJ9 performance page.
Bonus typo fix included elsewhere in page.
Closes #823

Broken Link to OpenJ9 FAQ

---

src/handlebars/support.handlebars

Fixes the table listing the release dates on the support page.
See https://twitter.com/michaelvitz/status/1321037223609946114?s=20 for details.

Fixes for table in support page

---

src/handlebars/archive.handlebars

Show type of checksum being used on archive page

---

src/js/common.js
src/json/config.json

update supported version for j9 15+

---

.github/workflows/linter.yml
.travis.yml

switch travis to github actions

---

.github/workflows/deploy-to-gh-pages.yml

actions: add production action

---

.github/workflows/unstage.yml

actions: automatically remove staged PR when merged

---

src/handlebars/index.handlebars

Remove the link to diary that is no longer used.
Closes #643

Remove further reference to calendar

---

src/handlebars/installation.handlebars

Explain how to use our packages on Debian and Ubuntu derivatives.

Improve deb instructions for derivatives

---

src/handlebars/installation.handlebars

Fix formatting of deb instructions

---

src/handlebars/support.handlebars

Signed-off-by: Stewart X Addison <sxa@redhat.com>

update support.html for 8u275-b01

---

src/handlebars/release_notes.handlebars

Fix typo on id for 8u272 identifier

---

src/json/config.json
src/json/config.schema.json

add alpine linux

---

package-lock.json
src/handlebars/nightly.handlebars
src/handlebars/releases.handlebars
src/handlebars/upstream.handlebars
src/js/archive.js
src/js/common.js
src/js/index.js
src/js/installation.js
src/js/nightly.js
src/js/releases.js
src/js/upstream.js
src/json/config.json
src/json/config.schema.json

Also removes the unnecessary binary and installer extensions from the config file

Add Windows aarch64

---

src/handlebars/partials/header.handlebars

Reverts AdoptOpenJDK/openjdk-website#885

Revert "Add banner for January 2021 releases"

---

src/handlebars/jmc.handlebars

Adds final JMC 8.0.0

---

src/handlebars/partials/header.handlebars
src/handlebars/partials/social-bar.handlebars

Update twitter/youtube links

---

src/json/config.json

rename alpine to make it clearer on website

---

.github/workflows/auto-merge.yml

Switch auto-merge.yml to use pull_request_target

---

src/handlebars/faq.handlebars
src/handlebars/installation.handlebars
src/handlebars/migration.handlebars
src/handlebars/quality.handlebars
src/handlebars/release_notes.handlebars
src/handlebars/support.handlebars
src/handlebars/supported_platforms.handlebars
src/scss/styles-7-support.scss

Fixing irrelevant css class name

---

src/handlebars/partials/header.handlebars

Add April CPU release banner

---

src/handlebars/support.handlebars

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

Update supports page to Apr 2021 releases

---

src/handlebars/release_notes.handlebars

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

Add Apr 2021 release notes

---

src/handlebars/release_notes.handlebars

Add Note about delay in Solaris builds

---

src/handlebars/partials/header.handlebars

Signed-off-by: Stewart X Addison <sxa@redhat.com>

Update banner to mention rebranding and to point to Adoptium.net for all new releases

---

src/handlebars/releases.handlebars
src/js/releases.js

add clear indication that temurin binaries come from adoptium.net

---

src/handlebars/releases.handlebars

add notice on semuru binaries to match temurin

---

src/handlebars/releases.handlebars

Fixes adoptium/adoptium.net#151
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Allow other Vendors to be labeled as Early Access

---

src/handlebars/releases.handlebars

as fixed in https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/480

Switch vendor from adoptium to eclipse

---

src/handlebars/jmc.handlebars

Fixing some minor errors and placing latest stable on top

---

src/handlebars/icedtea-web.handlebars

Add new IcedTea versions and ChangeLog/News link

---

src/handlebars/releases.handlebars
src/js/index.js
src/js/releases.js

Adds support for the newly added deep links https://github.com/adoptium/website-v2/pull/379

update redirect to use deep links

---

.github/workflows/deploy-to-gh-pages.yml
gulpfile.js
netlify.toml
package-lock.json
package.json

Bump build to Node 14
