AdoptOpenJDK/openjdk-website

- README.md
Nothing has changed with the current version of the website API, but updating the links to reflect the new domain.
> Update API description

- src/handlebars/installation.handlebars
- src/handlebars/partials/menu.handlebars
- src/js/0-global.js
- src/scss/styles-1-large-main.scss
https://staging.adoptopenjdk.net/
**NOTE FOR STAGING: Once again, the staging server has used a cached version of the CSS, so the menu is looking pretty strange at the moment.**
You can now add nested accordion-style submenus (with an unlimited number of sub-sub-menus) by adding the following simple `<li>` element structure instead of the standard single line:
**Standard menu entry:**
```
<li><a href="">Menu item 1</a></li>
```
**Nested submenu entry:** 
```
<li class="submenu"><a>Submenu parent</a>
<ul>
<li><a href="">Submenu child item 1</a></li>
<li><a href="">Submenu child item 2</a></li>
</ul>
</li>
```
> **Important:** the submenu parent `<li>` must have the class `submenu`
Also updated the Installation page to include checksum instructions for Linux, Mac, Windows
> Add twisty menu system & checksum instructions

- src/js/0-global.js
On [staging](https://staging.adoptopenjdk.net) (currently waiting on cache to clear for updates to be visible)
Naming and search of arm64 changed to aarch64.
Windows platform added in anticipation of the new builds.
However, Windows will not actually appear on the site until the builds are added.
> Change arm64 > aarch64, add Windows platform

- src/js/0-global.js
Addition to a string only, has no impact on existing functionality.
Required the additions to recognise some Windows-based OSes.
> Add more OS detection options for Windows

- .eslintignore
- CONTRIBUTING.md
- gulpfile.js
- package.json
- src/handlebars/partials/footer.handlebars
- src/handlebars/partials/header.handlebars
[STAGING](https://staging.adoptopenjdk.net)
Hashes are now automatically added to the filename of minified CSS and JS.
Links to these hashed files are then automatically injected into every HTML file, so there is no action needed on the part of the developer.
Browser-sync is also added, for instant automatic browser refreshes whenever a file in `/src` is saved.
Browser-sync also allows for easy testing on mobile devices, as explained in the new "PRO TIP" on Contributing.md.
> Add hashes to minified JS and CSS files, add BrowserSync (Fixes #108)

- gulpfile.js
- package.json
Fixed duplicate hashed file issue (which only occurred when you stopped the gulp service, made changes, then restarted the gulp service - thus bypassing the hash tracking process temporarily), and prevented any similar issues in the future, by adding `gulp-clean`. This destroys the existing `/dist` directory every time the main gulp process is started, meaning that the rest of the build can start from a clean sheet.
> Fix Gulp hashing issue

- .eslintrc.yml
- src/handlebars/installation.handlebars
- src/js/0-global.js
- src/js/installation.js
- src/js/nightly.js
- src/js/releases.js
- src/json/config.json
- src/scss/styles-1-large-main.scss
- src/scss/styles-3-nightly.scss
[ON STAGING - Installation](https://staging.adoptopenjdk.net/installation.html)
- The installation page is now dynamically populated, similar to the other main pages.
- The user has a drop-down list of platforms to choose from.
- If the user's OS is recognised and matches a supported platform, the relevant platform is selected and displayed on page load - UNLESS a platform has already been specified (via the URL, if for example you send someone a link to that specific platform installation instructions).
- The installation instructions now contain the EXACT commands that users will need to run, to install the latest binary for their selected platform (thanks for the suggestion @gdams)
- `config.js` contains the 'template' unzip, path, and checksum commands for each platform.
> WIP: Add dynamic installation page

- src/handlebars/archive.handlebars
- src/js/archive.js
- src/js/index.js
- src/scss/styles-1-large-main.scss
- src/scss/styles-11-archive.scss
Fixes #170 
[ON STAGING](https://staging.adoptopenjdk.net) 
Added capability for installers to be displayed on the Archive page and set capability and preference for installer on the main home page button.
> Add Installers to Home Page and Archive.

- src/handlebars/getinvolved.handlebars
Fix minor typo in the getinvolved page.
> Point to the right github page for tests.

- src/handlebars/index.handlebars
It's not obvious from our main web site that we provide docker images - this PR adds a link to the front page and makes it clear which repository on dockerhub is the one maintained by the adoptopenjdk project. Hopefully this isn't too controversial ;-)
> Add docker link to the front of the adoptopenjdk website

- src/handlebars/index.handlebars
Fixes https://github.com/AdoptOpenJDK/openjdk-website/issues/207 - open to alternative suggestions as to where to locate this on the page but here's my "starter for 10"
> Add link to the meetings diary

- src/handlebars/index.handlebars
- src/handlebars/partials/jck-tick.handlebars
- src/js/0-global.js
- src/js/archive.js
- src/js/releases.js
- src/scss/styles-4-releases.scss
This PR allows us to dynamically set which platforms are JCK approved for a specific platform release.
We will have a jck.json file in a release repo. It will look something like this:
```JSON
{
"jdk8u152-b16": {
"PPC64LE_LINUX": "true"
}
}
```
I have added a file here for testing: https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/blob/master/jck.json.
NOTE that the CSS doesn't look fantastic on this. Perhaps @EnriqueL8 could take a look and pick this up later on but for now this is the important work.
https://staging.adoptopenjdk.net/releases.html?variant=openjdk8-openj9#ppc64le_linux
> add dynamic JCK status

- src/handlebars/partials/jck-tick.handlebars
- src/js/0-global.js
- src/scss/styles-4-releases.scss
closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/228
This PR fixes #228 but also tidies up the way that the JCK tick appears (making it more inline)
staging: https://staging.adoptopenjdk.net
> a few bug fixes + tweaks

- src/scss/styles-2-index.scss
Div by default take 100% of height of parent element
due to transformation it was going out of bounds, and link were overflowing
> Fixed css for div.dl-description (#227)

- src/handlebars/support.handlebars
Added links to the web page of the three projects from which AdoptOpenJDK produces builds.  This makes those projects easier to find for those new to the fact that there are three options when choosing an OpenJDK build.
http://openjdk.java.net
https://www.eclipse.org/openj9/
https://sap.github.io/SapMachine/
Each link uses the _blank target as used by the links on the main page of AdoptOpenJDK page.
> Links to projects used for AdoptOpenJDK builds

- src/handlebars/slack.handlebars
Remove link to defunct Slack archive from Slack invitation page (https://adoptopenjdk.net/slack.html).
> Remove link to defunct Slack archive

- src/js/archive.js
- src/js/index.js
- src/js/releases.js
This makes the links consistent and improves the accuracy of error
messages.
See issue https://github.com/AdoptOpenJDK/openjdk-website/issues/276
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
> Updating the AdoptOpenJDK website to include the jvm variant.

- src/handlebars/banner.handlebars
- src/handlebars/partials/header.handlebars
This might not render well on staging as it already uses a different banner but this will work in production.
> change java 11 banner to use proper banner

- src/json/config.json
(Hopefully) Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/610 and https://github.com/AdoptOpenJDK/openjdk-website/issues/283
> WIP Re-add LinuxLH jdk8 builds & stop them being default

- src/js/installation.js
JRE archives contain a directory with `-jre` appended to the release name.  This PR ensures the installation page's PATH setup command includes the correct directory.
> Include the '-jre' directory suffix for JRE PATH setup.

- src/js/archive.js
This PR (related to #342) sorts archive releases by timestamp in descending order, which is consistent with GitHub releases, Oracle's archive page, etc.
There's also a minor tweak to reduce the number of `moment`s created.
> Sort archive releases by timestamp in descending order.  Addresses #342

- src/handlebars/archive.handlebars
- src/scss/styles-11-archive.scss
This PR adds a warning to the Archive page regarding use of old releases.
> Add a warning to the Archive page regarding use of old releases

- src/js/archive.js
- src/js/nightly.js
- src/js/releases.js
This is to address AdoptOpenJDK/openjdk-website#286, and uses the new property introduced by AdoptOpenJDK/openjdk-api#102.
> Use the provided release URL

- src/handlebars/archive.handlebars
- src/js/archive.js
This PR adds a handy per release link to the new download dashboard at http://dash.adoptopenjdk.net/
> add link to download stats

- src/handlebars/archive.handlebars
- src/handlebars/index.handlebars
- src/handlebars/installation.handlebars
- src/handlebars/releases.handlebars
- src/js/archive.js
- src/js/index.js
- src/js/installation.js
- src/js/releases.js
The main goal of this PR is to get stuff to show up as soon as possible.  For example, the version+JVM selectors only rely on the data from `config.json`, so there's no need to wait for both an API request and (failing) `jck.json` request to complete.
This also places the error container in a consistent way (see [index](https://adoptopenjdk.net/index.html?variant=openjdk9&jvmVariant=invalid), [releases](https://adoptopenjdk.net/releases.html?variant=openjdk9&jvmVariant=invalid), [archive](https://adoptopenjdk.net/archive.html?variant=openjdk9&jvmVariant=invalid), [nightly](https://adoptopenjdk.net/nightly.html?variant=openjdk9&jvmVariant=invalid)) and ensures the selectors don't disappear on an error (see [valid](https://adoptopenjdk.net/releases.html?variant=openjdk9&jvmVariant=hotspot) …
> Content loading tweaks

- package-lock.json
- src/handlebars/releases.handlebars
- src/js/0-global.js
- src/js/releases.js
- src/scss/styles-4-releases.scss
This PR reworks the Releases page to support displaying multiple binary types (e.g Installer, JDK, JRE), resolving #354.
> Rework the Releases page to support Installer+JDK+JRE

- src/js/nightly.js
- src/js/polyfill/Array.prototype.find.js
The Releases page redo included a call to [`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), which IE doesn't like.  This adds a polyfill to get it working again.
Another option would be to include [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) to avoid worrying about specific polyfills.
*edit:* I've added a small fix for the Nightly page, since IE also doesn't like [`String.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).
> Add 'Array.prototype.find' polyfill

- src/handlebars/index.handlebars
- src/json/config.json
- src/json/config.schema.json
The spelling of Oracle's VM in OpenJDK is 'HotSpot' instead of 'Hotspot'.
> Rename 'Hotspot' to 'HotSpot'

- gulpfile.js
- package-lock.json
- package.json
- src/handlebars/partials/header.handlebars
This PR introduces the `base64img` Handlebars helper, which converts images to their base64 representation, and uses it to address the 0.12KB logo's `alt` text flash/flicker (["AdoptOpenJDK six-square logo"](/AdoptOpenJDK/openjdk-website/blob/24cfba91d21e036eb3fc0acbe3a8e8f442e4084d/src/handlebars/partials/header.handlebars#L76)) that occurs on page loads.
It also switches `gulpfile.js` to arrow functions and replaces `var` with `const`.
> Inline the logo to prevent alt text flash, minor `gulpfile.js` tweaks

- CONTRIBUTING.md
- gulpfile.js
- src/handlebars/banner.handlebars
- src/handlebars/partials/header.handlebars
This PR simplifies things by inserting the banner/notice at build time, rather than on each client page load via https://www.w3schools.com/lib/w3data.js.  There is no benefit to dynamically loading `banner.html` on every page when Prod changes occur through PRs / Jenkins builds.
> Remove unnecessary complexity for the site banner/notice

- package-lock.json
- src/handlebars/partials/footer.handlebars
- src/js/common.js
- src/js/entry.js
- src/js/index.js
- src/js/releases.js
This PR fixes submenus and moves some lingering `global` assignments into `entry.js`.
> Fix menu twisties and centralize global assignments in 'entry.js'

- src/scss/styles-7-support.scss
fixes a bug which was introduced in https://github.com/AdoptOpenJDK/openjdk-website/commit/8df2bf9226bfe6ae4510dc6c17195b3f675ee3c3 which added a border to every `td` on the website
> fix sponsors page

- src/handlebars/archive.handlebars
- src/js/archive.js
- src/js/common.js
- src/scss/styles-11-archive.scss
This PR adds support for displaying multiple release assets (e.g. Installer, JDK, and JRE) on the Archive page.
Resolves #381
> Rework Archive page (Installer+JDK+JRE support)

- package-lock.json
- package.json
- src/json/config.json
Fix for #400. Replaces usages of non-standard `unzip` in Win32/64 installation string templates with an equivalent Powershell command: 
```powershell
Expand-Archive -Path .\FILENAME -DestinationPath .
```
> Update Windows install commands to use standard Powershell unzip

- src/handlebars/supported_platforms.handlebars
Mirrored the levels for OpenJDK 11, which I
believe are identical but having a separate
table provides the opportunity for some variation
if needed.
> Add platform tables for OpenJDK 12

- src/handlebars/supported_platforms.handlebars
For OpenJDK 8: Added Solaris table and included support
for Solaris 10 and 11 for HotSpot.
> Support table missing for Solaris

- src/handlebars/upstream.handlebars
- src/scss/styles-12-upstream.scss
Follow up for:
https://github.com/AdoptOpenJDK/openjdk-website/pull/446/
Specifically commit: 56c393c
> Add upstream builds to website (v2)

- src/handlebars/migration.handlebars
Currently the page on features has a tick next to OpenJFX11 with the words "Coming Soon". This should be a cross with the words "Coming Soon" to be consistent with how the other such items are displayed.
If anyone knows of a reason why it was a tick to begin
> Change tick to cross for OpenJFX (coming soon)

- src/handlebars/upstream.handlebars
JDK 11 only, as the Aarch64 port only got included in JDK 9+
> Add link to Aarch64 Linux build in upstream.html

- src/handlebars/migration.handlebars
Update migration.handlebars to include some user
information for IcedTea-Web as an optional install
component.
> Add migration information for IcedTea-Web

- src/handlebars/migration.handlebars
MSI installer for OpenJDK 11 also has optional
IcedTea-Web component. Update table and
migration section for IcedTea-web.
> Update migration for IcedTea-Web on OpenJDK 11

- src/handlebars/installation.handlebars
- src/handlebars/migration.handlebars
Add information to the installation page and
migration page to indicate that MSI installers are
supported only on x64 systems.
Also added a sentence to point to the new IcedTea-Web
downloads page from the migration guide.
> IcedTea web installer packages are x64 only

- src/handlebars/upstream.handlebars
Also add links to JDK 11 JRE builds produced via the legacy-images
target.
> Add new JDK 11 and JDK 8 EA builds to upstream.html

- src/handlebars/installation.handlebars
- src/handlebars/migration.handlebars
Fix the migration guide and the installation page
for AdoptOpenJDK 8 only.
Reference: https://github.com/AdoptOpenJDK/openjdk-installer/issues/120
> IcedTea-Web added only to v8 MSI installer

- src/handlebars/support.handlebars
Current entry appears to be a typo. There is no plan to release any
jdk12 builds in June.
The next release should be version 12.0.2, and should coincide with
the other quarterly releases (for jdk8 and jdk11) in July.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
> Correct jdk12 release and version

- src/handlebars/upstream.handlebars
Latest upstream EA tags are b6 for JDK 11 and b5 for
JDK 8, respectively.
> Update to JDK 11.0.4+6 and JDK 8u222-b05 EA builds

- src/json/config.json
- Copied from Win x64 variant
- Add 'Large Heap' to officialName
- Change heap size to 'large'
Related AdoptOpenJDK/openjdk-build#1099
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
> Add WinXL variant to config

- src/handlebars/upstream.handlebars
Let's use something less off-putting. The upstream project
will try to fix any bugs found even though there are no actual
SLAs.
> Update wording for "support" of OpenJDK Project Builds

- src/handlebars/installation.handlebars
- src/js/installation.js
Fixes #519, tested in IE11 and Firefox 67.
The existing method grabs text from the DOM using an injected ID param based on platform (e.g. `#java-X64_WIN`) and does not account for JDK vs JRE selection.
This change uses the more-generic `previousSibling` selector to grab the text content of its nearest preceding sibling.
> Fix incorrect file names showing up in copied installation commands

- src/handlebars/upstream.handlebars
AdoptOpenJDK tests were run on these:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/6/pipeline
These are the last EA builds for the 11.0.4/8u222 cycle. Trees are currently frozen.
> Update to JDK 11.0.4+9 and JDK 8u222-b07 EA builds

- src/handlebars/upstream.handlebars
The usual round of EA builds updates. JDK 8u222-b08 introduces new test failures in the `sanity.openjdk` suite. New tests got introduced between b07 and b08 some of them now fail as they
expose previously existing code issues.
See:
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-June/009735.html 
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-June/009667.html
That's an FYI. Test pipeline runs for this update:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/11/pipeline
> Update to JDK 11.0.4+10 and JDK 8u222-b08 EA builds

- src/handlebars/upstream.handlebars
GA tag for JDK 11:   jdk-11.0.4+11
GA tag for JDK 8:    jdk8u222-b10
> Add July 2019 CPU builds to upstream.html

- src/handlebars/upstream.handlebars
There have been concerns voiced that "Official Release" has a
connotation of being the one-and-only release, discrediting
other OpenJDK releases. Use a more neutral wording.
> [Upstream] Rename "Official Release" to "GA Release"

- src/handlebars/upstream.handlebars
Tested with `sanity.openjdk` and `sanity.system`:
JDK 11.0.5+1:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/43/pipeline
aarch64 re-run: https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_upstream_openjdk11_hs_sanity.openjdk_aarch64_linux/10/
JDK 8u232-b01: 
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/39/pipeline
Linux `sanity.system` failure seems intermittent. Need to investigate. Windows locale failure (testbug) is being investigated and going to be fixed upstream.
> Update to JDK 11.0.5+1 and JDK 8u232-b01 EA builds

- src/handlebars/upstream.handlebars
Tested with AdoptOpenJDK testing framework:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/47/pipeline
Aarch64 JDK 11 tests seems a test setup issue with many cores. Windows failures are the same as for 8u232-b01 (locale test) + one additional which we are looking into.
> Update to JDK 11.0.5+2 and JDK 8u232-b02 EA builds

- src/handlebars/users.handlebars
Jelastic is now has AdoptOpenJDK binaries in a list of available JDKs.
> Jelastic is added

- src/handlebars/upstream.handlebars
Update to fresh JDK 11 EA builds. No new builds for JDK 8 this week.
Sanity testing showed no issues:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/73/pipeline
> Update to JDK 11.0.5+5 EA builds

- src/handlebars/upstream.handlebars
Another round of upstream project builds update. Testing links:
JDK 11: https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/77/pipeline/64
JDK 8: https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/80/pipeline/
> Update to JDK 11.0.5+6 and JDK 8u232-b05 EA builds

- src/handlebars/upstream.handlebars
This should make it clearer that upstream builds are being built on Red Hat infrastructure (not AdoptOpenJDK's infrastructure).
> Mention "on their infrastructure" for upstream builds

- src/handlebars/index.handlebars
I've been asked to add "Red Hat built" for the upstream reference on the index page.
> Mention that Red Hat builds the upstream project builds

- src/handlebars/supported_platforms.handlebars
With OpenJDK 13 release, replaced OpenJDK 12 platform support with
that for OpenJDK 13. No change to supported OS's.
> Add supported platforms for OpenJDK 13, remove OpenJDK 12

- src/handlebars/upstream.handlebars
New round of upstream JDK 11 builds. Testing looks good:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/94/pipeline/61
> Update to JDK 11.0.5+8 EA builds

- src/handlebars/upstream.handlebars
Latest round of JDK 8u EA builds. No changes for JDK 11u.
> Update to JDK 8u232-b08 EA builds

- src/handlebars/upstream.handlebars
GA tag for JDK 11:   jdk-11.0.5+10
GA tag for JDK 8:    jdk8u232-b09
> Add October 2019 CPU builds to upstream.html

- src/handlebars/upstream.handlebars
jdk11u started with tagging EA builds. Here is the first batch, 11.0.6+1.
> Update to JDK 11.0.6+1 EA builds

- src/json/config.json
fixes: https://github.com/AdoptOpenJDK/openjdk-website/issues/605
> rename windows x32 to windows x86

- src/handlebars/upstream.handlebars
New round of JDK 11u EA builds. Unfortunately still no 8u EA builds yet.
Testing:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/147/pipeline/61
Not yet sure what to make of the aarch64 failures as we are not seeing them internally.
> Update to JDK 11.0.6+2 EA builds

- src/handlebars/upstream.handlebars
First round of JDK 8u242 EA builds.
Testing:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/154/pipeline/
> Update to JDK 8u242-b01 EA builds

- src/handlebars/upstream.handlebars
Latest round of JDK 11 EA builds.
Testing: https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/159/pipeline/63/
FWIW, jdk/java/net/CookieHandler/B6791927.java will be fixed with the next EA build, 11.0.6+4
> Update to JDK 11.0.6+3 EA builds

- src/handlebars/upstream.handlebars
Build 4 for JDK 11.0.6
Testing: https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/163/pipeline/63
> Update to JDK 11.0.6+4 EA builds

- src/handlebars/upstream.handlebars
New round of JDK 11 EA builds.
Testing: https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/172/pipeline
Windows issue seems a test setup problem?
> Update to JDK 11.0.6+5 EA builds

- src/handlebars/partials/header.handlebars
- src/handlebars/partials/menu.handlebars
- src/js/common.js
- src/scss/styles-1-large-main.scss
Some people like to browse with JS turned off. Making the menu open and close without JS is a relatively trivial thing, using HTML and CSS.
> noscript - make menu open and close without JS

- src/handlebars/upstream.handlebars
New round of upstream EA builds for JDK 8 and 11.
> Update to JDK 11.0.6+6 and 8u242-b04 EA builds

- src/handlebars/index.handlebars
Existing explanation implies that OpenJ9 is designed for
low memory usage and you might not choose it if your app
requires a lot of memory. Change the word "usage" to "footprint"
for more clarity.
> More clarity for why choose OpenJ9

- src/handlebars/upstream.handlebars
Latest round of EA builds updates.
Testing:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/215/pipeline
JDK 11 Aarch64 VarHandle weak CAS failures are being investigated.
> Update to JDK 11.0.6+9 and 8u242-b05 EA builds

- src/handlebars/upstream.handlebars
Latest upstream JDK 8u EA build as of today.
Testing (in progress):
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/217/pipeline
> Update to JDK 8u242-b06 EA builds

- src/handlebars/upstream.handlebars
GA tag for JDK 11:   jdk-11.0.6+10
Upstream release announcement:
http://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-January/002374.html
Testing at AdoptOpenJDK in progress here:
https://ci.adoptopenjdk.net/blue/organizations/jenkins/UpstreamAutotest/detail/UpstreamAutotest/225/pipeline
> Add January 2020 CPU builds for JDK 11 to upstream.html

- src/handlebars/installation.handlebars
Fix typo: `apt-get-update` to `apt-get update`
- [x ] documentation is changed or added (if applicable)
> Fix typo on apt-get command

- src/handlebars/installation.handlebars
Follow up for #683.
Add single quotes to here document to disable variable replacement on shell.
Use yum variables for repository configuration, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_yum_variables
> Fix CentOS repository example

- src/handlebars/support.handlebars
Changed the end of availability for AdoptOpenJDK 8 binaries to match the public dates for Red Hat's (OpenJDK 8u stewards) end of support for OpenJDK 8.
https://access.redhat.com/articles/1299013
> [WIP] Update Java 8 end of availability

- src/handlebars/support.handlebars
Update to availability dates.
For Java 11 date move see https://github.com/AdoptOpenJDK/TSC/issues/145
> Update Java 14 availability and Java 11 EOS dates

- src/handlebars/installation.handlebars
Was authoring a "howto" YouTube video and discovered that some commands are missing `sudo` whereas others have `sudo`.
This PR uses `sudo` in all apt examples for consistency:
> ![image](https://user-images.githubusercontent.com/6345473/77089670-7e3efc00-69dc-11ea-8eac-c14d0c0e191a.png)
> Use sudo for all apt commands

- src/handlebars/faq.handlebars
Many open issues request bundling OpenJFX/JavaFX with AdoptOpenJDK. Considering the discussions I gathered on our Slack and the support situation, this is most likely not going to happen. Therefore, I decided to summarize the situation in our FAQ so that there's something I can point people at.
If this gets approved, I plan to close all requests for OpenJFX/JavaFX. I do not want to link them here right now because I assume this is a hot-button issue.
A formal decision by the @AdoptOpenJDK/tsc might be necessary, too.
> Add dedicated OpenJFX FAQ

- src/handlebars/releases.handlebars
- src/js/common.js
- src/js/releases.js
- src/scss/styles-4-releases.scss
This PR adds an early access tag:
```js
if ((version.pre) && (version.pre == 'ea')) {
return true
} else { 
return false
}
```
Sample:
> allow website to show ea builds

- src/handlebars/installation.handlebars
fix doc with INSTALLDIR when folder contains space
https://github.com/AdoptOpenJDK/openjdk-installer/issues/223
> quote path with space

- src/handlebars/migration.handlebars
Migration page still shows OpenJFX as "coming soon".
Modified the table to remove "coming soon" and changed the content in the OpenJFX section.
Link users to the OpenJFX FAQ.
> Update migration page for OpenJFX

- src/handlebars/supported_platforms.handlebars
AIX builds of OpenJ9 will now only run on AIX 7.1.5.5 or later as we had to change the build machines in order to support some new functionality (That level has an updated version of the `dump` command)
> Adjust minimum AIX level for OpenJ9 bulids to 7.1.5.5

- src/handlebars/supported_platforms.handlebars
CentOS8 is not yet available on s390x but this will add RHEL8. @smlambert I explicitly want your confirmation that you're happy with this before adding it given that we don't have systems running this level across ll platforms at present.
> Add RHEL/CentOS8 as supported platforms

- src/handlebars/supported_platforms.handlebars
At the moment the supported platforms pages have nothing listed for arm32/armv7l/aarch32
> Add arm32 Ubuntu distributions as supported

- src/handlebars/partials/menu.handlebars
The project calendar is not used, and choosing this menu option results in ERR_NAME_NOT_RESOLVED.
Closes #643
> Remove menu option for Meeting diary

- src/handlebars/support.handlebars
The Support page contains variations of Sept and September and no standardisation in month naming. This PR changes all instances of `Sept` on the support page to `September`
Signed-off-by: Morgan Davies morgandavies2020@gmail.com
> Standardise Month Naming on support.html

- src/json/config.schema.json
This PR adds a schema definition for the `platform.attributes` object used in `config.json`.
> Add JSON schema definition for platform.attributes object

- src/handlebars/faq.handlebars
According to https://github.com/AdoptOpenJDK/openjdk-build/issues/577#issuecomment-732978013, ojdkbuild is a viable source for OpenJFX 8 builds. This PR adds it to the OpenJFX FAQ.
cc @jschwartzenberg
> Add ojdkbuild as possible OpenJFX source

- src/handlebars/faq.handlebars
The change in #855 went into the section for OpenJFX 11 instead of the section for OpenJFX 8 :facepalm:. This is now fixed.
> Move ojdkbuild reference to correct section

- src/js/releases.js
This PR fixes #897 by replacing `append()` with `appendChild()`. Unfortunately [append doesn't work in all browsers](https://caniuse.com/mdn-api_parentnode_append) and as the code appends a DOM node, `appendChild()` can be used as well.
> Replaced append() with appendChild() to fix IE11 incompatibility (fixes #897)

- src/handlebars/jmc.handlebars
Hello, I noticed that the JMC snapshot links are outdated. Since master and 8.x.x are distinct jobs, I made distinctive sections as well for 8.1.0 and 8.0.0 builds.
However this PR is slightly incomplete as there's no job for the _tagged_ (RC / GA) jmc releases.
* https://ci.adoptopenjdk.net/view/JMC/job/jmc-build/
* https://github.com/openjdk/jmc/releases/tag/8.0.0-ga
> JMC 8.x snapshot build links

- src/handlebars/support.handlebars
This incorrectly listed a date of the 19th which was the date for the October releases, not the September JDK17 one.
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> Fix date for JDK17 GA in support.html

- src/handlebars/faq.handlebars
This updates the link of the "Java is Still Free" post on Medium to a newer version.
There is a notice on the original post to only read this version for historical context:
> A NEWER VERSION (2.0.1) HAS BEEN RELEASED — PLEASE ONLY READ THIS DOCUMENT FOR HISTORICAL CONTEXT
> Update link to "Java is Still Free" in FAQ

- src/handlebars/releases.handlebars
There is a spelling mistake (Semuru) and also the word "Semeru" should really be
"Semeru Runtimes" (which is the correct phrase).
Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>
> Fix Semeru Runtimes references on releases page

- src/handlebars/jmc.handlebars
Updated the JMC Website part to include the latest 8.1.0 version
> Updated website for JMC 8.1.0

- src/handlebars/installation.handlebars
Make sure the owner of /usr/share/keyrings/adoptopenjdk-archive-keyring.gpg is always root rather than the user who did the Debian repository installation.
As far as I know having the keyring owned by non-root isn't a (realistically exploitable) security problem, since the user who created the keyring is going to be an administrative user, and even then only root the repo is served over HTTPS and only root can change its URL, but better keep things simple and clean.
Fixes: 4eebc787 ("Update on Ubuntu/Debian instruction (#985)")
> Debian repository installation: Keyring should be owned by root

- src/handlebars/installation.handlebars
The chown command in #1080 is obviously wrong, as it should be applied to the path of the file after moving, not the one before moving.
> Debian repository installation: Fix path to keyring in chown

- assemble.sh
- package.json
- src/handlebars/index.handlebars
- src/js/index.js
This PR overrides the action of the main blue home button to redirect users to either Adoptium or Semuru
Preview Link is https://6154536f87b8dd136f39320b--vibrant-hugle-19d716.netlify.app/
> add further download redirections to home page

- src/handlebars/upstream.handlebars
OpenJDK Project Builds will no longer be done for 11 and 8.
July CPU was the final release of this service.
The plan is to redirect to temurin releases going forward (October
timeframe). For now, advise users that no more releases will be
provided.
> Change banner for upstream binaries.

- src/handlebars/upstream.handlebars
Remove listing of old upstream builds and clarify where users should now get builds.
> Remove old upstream build access via website
